version: '3.8'

services:
  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d:ro
      - mysql_data:/var/lib/mysql

  backup:
    container_name: mysql_backup
    image: ubuntu:22.04
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backup-scripts:/scripts
      - ./backup-scripts/log.txt:/var/log/backup.log
    entrypoint:
      - /bin/bash
      - -c
      - |
        # Atualiza e instala pacotes básicos
        apt update
        apt install -y curl gnupg2 lsb-release cron

        # Baixa e instala o repositório Percona
        curl -O https://repo.percona.com/apt/percona-release_latest.generic_all.deb
        apt install -y ./percona-release_latest.generic_all.deb

        # Configura e instala o XtraBackup
        percona-release setup pxb-80
        apt install -y percona-xtrabackup-80
        xtrabackup --version
        
        mkdir backups

        (crontab -l 2>/dev/null; echo "* * * * * /scripts/backup.sh incremental >> /scripts/log.txt 2>&1") | crontab -
        (crontab -l 2>/dev/null; echo "*/5 * * * * /scripts/backup.sh full >> /scripts/log.txt 2>&1") | crontab -
        
        cron -f

volumes:
  mysql_data:
